version: '2'
services:

  mysql:
    image: mariadb
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
       MYSQL_DATABASE: wp
       MYSQL_USER: uwp
       MYSQL_PASSWORD: 123456
       MYSQL_ROOT_PASSWORD: 123456789
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    links:
      - wordpress
    restart: always


  wordpress:
    image: wordpress:php7.2-fpm
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    environment:
       WORDPRESS_DB_NAME: wp
       WORDPRESS_DB_USER: uwp
       WORDPRESS_TABLE_PREFIX: wp_
       WORDPRESS_DB_HOST: mysql
       WORDPRESS_DB_PASSWORD : 123456
    links:
      - mysql:mysql
    restart: always
